export const tabsName = [
  { key: "diagnoses", value: "Diagnose" },
  { key: "familyMemberDiagnoses", value: "Familienanamnese" },
  { key: "ecogStatus", value: "ECOG-Performance-Status-Befund" },
  { key: "specimens", value: "Tumorproben" },
  { key: "rebiopsyRequests", value: "Rebiopsie-Auftrag" },
  { key: "molecularPathologyFindings", value: "Molekular-Pathologie-Befund" },
  { key: "histologyReports", value: "Histologie-Berichte" },
  { key: "ihcReport", value: "IHC-Bericht" },
  { key: "histologyReevaluationRequests", value: "Histologie-Reevaluations-Auftrag" },
  { key: "recommendations", value: "Therapie-Empfehlung" },
  { key: "molecularTherapies", value: "Systemische Therapie" },
  { key: "response", value: "Molekular-Therapie-Befund" },
  { key: "previousGuidelineTherapies", value: "Leitlinien-Therapie" },
  { key: "studyInclusionRequests", value: "Studien-Einschluss-Empfehlung" },
  { key: "carePlans", value: "Therapieplan" },
  // {key: "", value: "Follow-up"},
  { key: "claims", value: "Kostenübernahme Antrag" },
  { key: "claimResponses", value: "Kostenübernahme Antwort" },
]
